export default {
  NAVIGATION_ITEM: 'NAVIGATION_ITEM',
  NAVIGATION: 'NAVIGATION',
  PLUGIN_UPDATE: 'PLUGIN_UPDATE',
  PLUGIN_SELECTED: 'PLUGIN_SELECTED',
  PLUGIN_TYPE: 'PLUGIN_TYPE',
  SIDEBAR_ACTIVE: 'SIDEBAR_ACTIVE',
  ABOUT_MORE_MENU_ITEM: 'ABOUT_MORE_MENU_ITEM',
  HOME: 'HOME',
  HOME_ITEM: 'HOME_ITEM',
  HOME_SOCKET: 'HOME_SOCKET',
  HOME_SIDEBAR_ACTIVE: 'HOME_SIDEBAR_ACTIVE',
  PROXY: 'PROXY',
  EXPLORE: 'EXPLORE',
  EXPLORE_MIDDWAY_ITEM: 'EXPLORE_MIDDWAY_ITEM'
}
