export default {
  NAVIGATION_ITEM: 'NAVIGATION_ITEM',
  NAVIGATION: 'NAVIGATION',
  PROGRESS_DISPLAY: 'PROGRESS_DISPLAY',
  ABOUT_MORE_MENU_ITEM: 'ABOUT_MORE_MENU_ITEM',
  HOME: 'HOME',
  HOME_ITEM: 'HOME_ITEM',
  HOME_SOCKET: 'HOME_SOCKET',
  ABOUT: 'ABOUT',
  EXPLORE: 'EXPLORE',
  EXPLORE_MIDDWAY_ITEM: 'EXPLORE_MIDDWAY_ITEM'
}
